import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession } from "@/actions/userActions";
import NavbarMain from "@/components/navbarMain";
import SideNavbar from "@/components/sideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                {!session.isLoggedIn ? (
                    <>
                        <NavbarMain />
                        <section className="block c700:flex container gap-4">
                            <SideNavbar />
                            {children}
                        </section>
                    </>
                ) : (
                    <h1>Please Logged in</h1>
                )}
            </body>
        </html>
    );
}
